name: delta_trace_studio
description: "The official open source editor for DeltaTraceDB."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # official packages
  intl: any
  flutter_launcher_icons: ^0.14.4
  web: ^1.1.1
  file_selector: ^1.0.3
  url_launcher: ^6.1.5

  # original packages
  simple_widget_markup: ^45.1.0
  simple_managers: any
  simple_locale: any
  file_state_manager: ^2.0.0
  delta_trace_db: ^0.0.40

  # other packages
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/layout/en/main_page/any/main_page.spwml
    - assets/layout/en/main_page/any/db_view_how_to_use.spwml
    - assets/layout/en/main_page/any/db_view_list.spwml
    - assets/layout/en/main_page/any/db_view_log.spwml
    - assets/layout/en/main_page/any/db_view_tree.spwml
    - assets/layout/en/main_page/any/filter_dialog.spwml
    - assets/layout/ja/main_page/any/main_page.spwml
    - assets/layout/ja/main_page/any/db_view_how_to_use.spwml
    - assets/layout/ja/main_page/any/db_view_list.spwml
    - assets/layout/ja/main_page/any/db_view_log.spwml
    - assets/layout/ja/main_page/any/db_view_tree.spwml
    - assets/layout/ja/main_page/any/filter_dialog.spwml

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.ttf
          weight: 400